export const nexusAssets = {
  heroRoom: "/hotel-nexus/hero-room.jpg",
  warriorStations: "/hotel-nexus/warrior-stations-interface.png",
  heartRateMonitoring: "/hotel-nexus/heart-rate-monitoring.png",
  stationDetail: "/hotel-nexus/station-detail.png",
  setupConsole: "/hotel-nexus/setup-console.png",
  tvWorkout: "/hotel-nexus/tv-workout.jpg",
  workoutSelection: "/hotel-nexus/workout-selection.png",
  roomWorkoutScreen: "/hotel-nexus/room-workout-screen.png",
  deviceMockup: "/hotel-nexus/device-mockup.png",
  ipadInterface: "/hotel-nexus/ipad-interface.jpg",
  stationPod: "/hotel-nexus/station-pod.jpg",
  roomWorkoutAction: "/hotel-nexus/room-workout-action.jpg",
  rooftopGym: "/hotel-nexus/rooftop-gym.jpg",
  dashboard: "/hotel-nexus/dashboard.jpg",
  mealSelection: "/hotel-nexus/meal-selection.png",
  recoveryMeal: "/hotel-nexus/recovery-meal.png",
  bodyScanner: "/hotel-nexus/body-scanner.png",
  bodyAnalytics: "/hotel-nexus/body-analytics.png",
  deviceMockupLarge: "/hotel-nexus/device-mockup-large.png",
};
